language: python
sudo: false
branches:
only:
  - master
python:
  - "2.7"
  - "3.5"
  - "3.6"

allow_failures:
    python:
        - 3.6

env:
  - PYSAL_PLUS=false
  - PYSAL_PLUS=true

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --add channels conda-forge
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env

install:
  - conda install --yes pip
  - conda install --yes --file requirements.txt;
  - pip install libpysal
  - cd esda

script:
  - python setup.py sdist >/dev/null
  - nosetests -v --with-coverage --cover-package=esda;

notifications:
    email:
        recipients:
            - levi.john.wolf+travis@gmail.com
            - sjsrey+travis@gmail.com
        on_change: always
        on_failure: always

after_success:
  - coveralls
